### ISSUE TITLE
Using the API

### ISSUE THREAD

**Issue by smiggle0404** [kicjow/Block-Particles#1]
Hey i'm trying to use the API you provided but I can't seem to get it working. 
Here's my section of code below, all i'm trying to do at the moment is have a certain command create a block particle.
http://pastebin.com/RCLBi4Wv

When I type the command in-game, the console is spammed with errors until I restart the server.
Each error is the same one spamming:

http://pastebin.com/aZ9bfT7i

**Comment by kicjow** [comment]
Hello it seems the problem is your not giving a world name.
World world = Bukkit.getServer().getWorld(getName());
getName() needs to be a string if your using getWorld.
So do like this
World world = Bukkit.getServer().getWorld("world");
or a better way is this
World world = player.getWorld();

**Comment by smiggle0404** [comment]
Thanks alot ^_^
