### ISSUE TITLE
1.11 Support

### ISSUE THREAD

**Issue by PaziHD** [kicjow/Block-Particles#2]
I really love this plugin, and it sortof works with 1.11 but its very buggy and shoots out tons of errors. I don't really care about the 1.11 particles, I just need to suppress the errors.

Here's a link of someone's updated Inventivetalent:ParticleLib - https://dl.dropboxusercontent.com/s/1utuhti6r84ct39/particleapi-2.1.1-shaded.jar
And ReflectionHelper is already updated.
I hope you can update this.. and the plugin isn't abandoned. Thanks.

**Comment by kicjow** [comment]
Thanks, I hope it works <3

**Comment by PaziHD** [comment]
Do we have any progress? I'm really hoping this works.

**Comment by kicjow** [comment]
I have the original imbedded into mine and when I decompiled this 1 and tried I couldn't get it to work.

**Comment by PaziHD** [comment]
Another lead: https://github.com/GamerBah/ParticleAPI/
Otherwise I think you might have to use another API like this one: https://www.spigotmc.org/resources/api-particle-effects-1-8-1-9-1-10-1-11.34896/

**Comment by kicjow** [comment]
Thanks a lot. The 1st link had an updated version which works great.
