### ISSUE TITLE
minor

### ISSUE THREAD

**Issue by QueenKisaki** [kicjow/Block-Particles#5]
well i updated but its saying:
21.06 16:33:11 [Server] INFO BlockParticles: 1.9.6 now available.
:)

**Comment by smmmadden** [comment]
I confirm the same with BungeeCord 1.12 / Spigot 1.12 and 1.9.7 of the plugin reporting 1.9.6 is available (true - but so is 1.9.7). :-)

**Comment by kicjow** [comment]
Ya, don't worry that is because the website it's checking the version on is down. I'll be fixing it when it comes back on

**Comment by kicjow** [comment]
Has been fixed.
