### ISSUE TITLE
My server can't upload the plugin and I get an error..

### ISSUE THREAD

**Issue by BelleGoBelle** [kicjow/Block-Particles#7]
Hello!

A few days ago I originally downloaded Block Particles, then removed it from my server.

I then redownloaded it and now it won't upload to the server and I get this error:

https://pastebin.com/tDeqRR3e

How can I fix this?

**Comment by emanh1** [comment]
Use Java 8

**Comment by BelleGoBelle** [comment]
I installed it and it's still not working.

**Comment by smmmadden** [comment]
What does the server console look like during startup?  
If you have an existing blockparticles that didn't load, remove that folder.
Does the BlockParticles folder get created under the plugins/ folder after a server restart along with 2 yml files?
Please share the startup of the server so we can see what may be causing it.  Saying it isn't working isn't helpful actually - need to see the facts on what exactly isn't working. :-)

**Comment by BelleGoBelle** [comment]
So, I started up the server and got the same error, But it's still showing that I have Java 7, While I just downloaded Java 8, enabled it and I checked, then restarted my PC. When I checked, it says the version is the current one out. 

I have no idea why it's doing this. The error is here: https://pastebin.com/aZJTFgY2

I also apologize for this, I'm still new to the whole plugin system thing. :P 

The Java verison right now I have is:
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by smmmadden** [comment]
if you never uninstalled the old version and installed the new version it explains why the server still starts but is using it.
If after  you installed Java 8, you did not change the startup script or the environment settings to use the new Java version, that would also explain why Java 7 is still being called.

**Comment by BelleGoBelle** [comment]
Problem fixed, Thank you! Java 8 was installed onto the server successfully.
