### ISSUE TITLE
PlayerPickupItemEvent WARN

### ISSUE THREAD

**Issue by andris155** [kicjow/Block-Particles#8]
`31.07 20:22:45 [Server] WARN "BlockParticles v1.9.7.1" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void me.badbones69.blockparticles.Api.onitemPickUp(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors []`

**Comment by kicjow** [comment]
Thanks, I am aware of this and I'll be posting the update soon.
